// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbmQmHF6_zKw-zi98A-ZWfpoHtyuCKh0Y',
    appId: '1:57219912522:web:cb8d8507bb21bab64627b3',
    messagingSenderId: '57219912522',
    projectId: 'tabungan-online-app',
    authDomain: 'tabungan-online-app.firebaseapp.com',
    storageBucket: 'tabungan-online-app.firebasestorage.app',
    measurementId: 'G-KJVBNBEGMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcmpNz_bhBr57AF1iTNJp1W_Nx5ukZyc4',
    appId: '1:57219912522:android:ef719a73cda814c54627b3',
    messagingSenderId: '57219912522',
    projectId: 'tabungan-online-app',
    storageBucket: 'tabungan-online-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdL8hV650NIHRxTjaAkNG9NMJI4zPLcUU',
    appId: '1:57219912522:ios:9940b8418959acf04627b3',
    messagingSenderId: '57219912522',
    projectId: 'tabungan-online-app',
    storageBucket: 'tabungan-online-app.firebasestorage.app',
    iosBundleId: 'com.tabungan.tabunganFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdL8hV650NIHRxTjaAkNG9NMJI4zPLcUU',
    appId: '1:57219912522:ios:9940b8418959acf04627b3',
    messagingSenderId: '57219912522',
    projectId: 'tabungan-online-app',
    storageBucket: 'tabungan-online-app.firebasestorage.app',
    iosBundleId: 'com.tabungan.tabunganFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbmQmHF6_zKw-zi98A-ZWfpoHtyuCKh0Y',
    appId: '1:57219912522:web:998309104f8722404627b3',
    messagingSenderId: '57219912522',
    projectId: 'tabungan-online-app',
    authDomain: 'tabungan-online-app.firebaseapp.com',
    storageBucket: 'tabungan-online-app.firebasestorage.app',
    measurementId: 'G-1GG31JKGE8',
  );
}
